---
title: "psyia3comp3021"
output: html_document
date: "2023-04-21"
---
Packages needed for visualisation
```{r}
install.packages("colorspace", "plotly", "dplyr", "ggplot2", "tidyverse", "GGally")
```

```{r}

library(ggplot2)
library(dplyr)
library(data.table)
library(plyr)
library(gridExtra)
library(plotly)
library(htmlwidgets)
library(tidyverse)
library(GGally)
```

Data pre processing and visualization (limited as the data was in good shape)
```{r}
df <- read.csv("playerStats.csv", sep = ";")
head(df)

#R does not do well at encoding accents on player names so here i will fix this (commented out after ran so i don't accidentaly re run)
df$Player <- iconv(df$Player, from = "ISO-8859-1", to = "UTF-8")

#Manually created a table to show the information
null_df <- data.frame(
valid= c("null", "not null"),
count = c(1, 2920)
)

null_df

#removes the first column
rmRankNull <- df[,-1]

#Removes player containing a null row
rmRankNull <- rmRankNull[-1532,]
df <- rmRankNull
```


Data description
```{r}
age_boxplot <- ggplot(df, aes(x=Comp, y=Age, fill=Comp)) + geom_boxplot()+ labs(x = "League")
age_boxplot <- ggplotly(age_boxplot, tooltip = c("Comp", "Age"))
age_boxplot
#Making the chart a widget so i ca add it to my webpage


#bp_widget <- as_widget(age_boxplot)
#saveWidget(bp_widget, "ageBoxplot.html")
```

BarPlot
```{r}
m <- select(df, Player,Comp, MP, Min)
#A football game lasts 90 minutes, next I'll create an expected minutes column, showing the matches played in minutes (90 per game)
mPlayed <- m %>% mutate(expMin = MP*90)
#Separate into leagues
engM <- subset(mPlayed,Comp == "Premier League" )
spaM <- subset(mPlayed,Comp == "La Liga" )
gerM <- subset(mPlayed,Comp == "Bundesliga" )
fraM <- subset(mPlayed,Comp == "Ligue 1" )
itaM <- subset(mPlayed,Comp == "Serie A" )
#Get the Avg expected and actual minutes per team , acknowledge the grouby and summarize dunction can be used
engMin <- mean(engM$Min)
engEx <- mean(engM$expMin)
spaMin <- mean(spaM$Min)
spaEx <- mean(spaM$expMin)
gerMin <- mean(gerM$Min)
gerEx <- mean(gerM$expMin)
fraMin <- mean(fraM$Min)
fraEx <- mean(fraM$expMin)
itaMin <- mean(itaM$Min)
itaEx <- mean(itaM$expMin)
#Creaeting the dataframe
```

Barplot
```{r}
minDf <- data.frame(
league = c("Bundesliga", "La Liga", "Ligue 1", "Premier League", "Serie A"),
avExpMin = c(gerEx, spaEx, fraEx, engEx, itaEx),
avMin = c(gerMin, spaMin, fraMin, engMin, itaMin)
)
minDf
#Plotting the values into stacked bar chart
mpBar <- ggplot(minDf, aes(x = league)) +
geom_col(aes(y = avExpMin, fill = "Expected Minutes"), position = "dodge") +
geom_col(aes(y = avMin, fill = "Actual Minutes"), position = "dodge") +
scale_fill_manual(values = c("lightpink", "steelblue")) +
labs(title = "Matchces Played (in minutes) vs Actual Minutes",
x = "League",
y = "Minutes Played") +
theme_classic()
mpBarPlot <- ggplotly(mpBar, tooltip = c("avExpMin", "avMin"))
mpBarPlot
#mp_widget <- as_widget(mpBarPlot)
```

Q1
```{r}
#saveWidget(mp_widget, "matchesPlayed.html")
#Narrowing dataset to hold relevant information
q1df <- select(df, Player, Age, Pos, Comp, DriAtt, Min)
#Next I want to select players who have at least played 10 minutes (some players can come on for a few minutes and not even touch the ball)
q1df <- subset(q1df, Min > 9)
q1df
#Next i want to add an age group column (catergorical column )
q1df$AgeGroup <- cut(q1df$Age, breaks = seq(16, 42, by = 3),
labels = c("16-18", "19-21", "22-24", "25-27", "28-30",
"31-33", "34-36", "37-42"))
#Next I'm going to group by the age groups and present the mean for each
q1df2 <- q1df %>%
drop_na(Player, Age, Pos, Comp, DriAtt, Min, AgeGroup)  %>%
group_by(AgeGroup)  %>%
summarise('AvDriAtt' = mean(DriAtt))
q1df
q1df2
q1pl <- ggplot(q1df2, aes(x=AgeGroup, y=AvDriAtt)) +
geom_bar(stat = "identity", fill = "steelblue")+labs(title = "Does player age determine the frequency in which players dribble with the ball",
x = "Age Groups",
y = "Average Dribble Attempts") +
theme_classic()
q1pl <- ggplotly(q1pl, tooltip = c("AvDriAtt"))
q1pl
```

Q2
```{r}

#Narrow DF
q2df <- select(df, Player, Age, Comp, Off, MP, Pos)
#Want players who have played 5+ matches (played against different backlines)
q2df <- subset(q2df, MP >4)
#selecting 95th percentile and above (Want most relevant data , only certain people run offside)
q2df <- subset(q2df, Off > quantile(0.95))
q2df
q2pl <- ggplot(q2df, aes(x=Age, y=Off, a =Player, b=Comp, c= MP, color = Comp)) +
geom_point()+labs(title = "Do younger players tend to be offside more?",
x = "Player Age",
y = "Offsides per game") +
theme_classic()
#Shows a range of information on hover now, no information overload
q2pl <- ggplotly(q2pl, tooltip = c("Age", "Off", "Player", "Comp", "MP"))
q2pl
```

Q3
```{r}
#Narrow the DF
#Left out 2CrdY because players rarely get 2 yellows in a game and would be included in yellow cards average
q3df <- select(df, Player, Comp, Fls, CrdY, CrdR, MP, Squad, Pos)
q3df <- q3df %>% subset(Squad == "Arsenal" & MP>1)  %>% arrange(CrdR)
#Makes the tool tip more informative with proper names
names(q3df)[4] <- "YellowCards"
names(q3df)[5] <- "RedCards"
names(q3df)[6] <- "MatchesPlayed"
q3df
chr <- ggplot(q3df, aes(x=Fls, y = YellowCards, a= Player,b=MatchesPlayed, color=RedCards )) + geom_point() + labs(title = "What Player In The Arsenal Squad Had The Worst Misconduct?", x = "Average Fouls Per Game",
y = "Number of Yellow cards", color = "Number of Red cards") + scale_color_gradient(low="green", high="red")
chr <- ggplotly(chr, tooltip = c("Player", "Fls", "YellowCards", "RedCards", "MatchesPlayed"))
chr

```

Q4
```{r}
q4df <- df %>% subset(Squad == "Arsenal"  & (Pos =="MF" | Pos == "MFFW"| Pos == "MFDF")) %>% select(Player, Squad,MP,Min, PasTotCmp.,DriSucc, Sw, PasProg) %>% mutate(PasTotCmp. = PasTotCmp./100)
#Turn passing percentage to decimal
names(q4df)[5] <- "PassesCompleted"
names(q4df)[6] <- "SuccessfulDribbles"
names(q4df)[7] <- "Switches"
names(q4df)[8] <- "ProgressivePasses"
q4df


eg <- ggparcoord(q4df,
columns = 5:8, groupColumn = 1,scale="globalminmax", showPoints = TRUE
)+labs(title = "Which Arsenal Midfielder Was Best In Possesion?", x= "Average Passing Statistics", y = "Value (Actual Values)" )+theme(axis.text.x = element_text(angle = 90, hjust = 1))

ch <- ggparcoord(q4df,
columns = 5:8, groupColumn = 1, scale="uniminmax", showPoints = TRUE,
)+labs(title = "Which Arsenal Midfielder Was Best In Possesion?", x= "Average Passing Statistics", y = "Value (Normalised)" )+theme(axis.text.x = element_text(angle = 90, hjust = 1))

#This produces a chart that is not normalised
q4chart <- ggplotly(eg)

#Normalised chart
q4chartNorm<- ggplotly(ch)

q4chart
q4chartNorm
```


Q5
```{r}
#Narrow DF
#Want players who have played 5+ matches (played against different back lines)
#selecting 95th percentile and above (Want most relevant data , only certain people run offside)
q5df <- df %>% select( Player, Age, Comp, Off, MP, Pos, Press) %>% subset( MP >4)  %>%  subset( Off > quantile(0.95))
q5df
q5ch <- ggplot(q5df, aes(x=Press, y=Off, a =Player, b=Comp, c= MP, color =Comp )) +
geom_point()+labs(title = "Do players who tend to be offside more press less??",
x = "Player Presses Per Game",
y = "Offsides per game") +
facet_wrap(~ Comp) +
theme_classic()
#Shows a range of information on hover now, no information overload
q5ch <- ggplotly(q5ch, tooltip = c("Press", "Off", "Player", "Pos", "MP"))
q5ch
mp_widget <- as_widget(q5ch)
saveWidget(mp_widget, "q5ch1.html")
```


Q7

```{r}

q7df <- df %>% subset(Squad != "Arsenal" & (Pos == "MF" | Pos == "MFFW" | Pos == "MFDF")) %>%
  select(Player, Squad, MP, Min, PasTotCmp., DriSucc, Sw, PasProg, Comp) %>%
  mutate(PasTotCmp. = PasTotCmp. / 100) %>%
  drop_na(Player, Squad, MP, Min, PasTotCmp., DriSucc, Sw, PasProg, Comp) %>%
  group_by(Comp) %>%
  summarise('PassesCompleted' = mean(PasTotCmp.), 'SuccessfulDribbles' = mean(DriSucc),
            'Switches' = mean(Sw), 'ProgressivePasses' = mean(PasProg))

ch7 <- ggparcoord(q7df,
                  columns = 2:5, groupColumn = 1, scale = "globalminmax", showPoints = TRUE) +
  labs(title = "Where do Arsenal's Midfielders Rank against Europe's top 5 leagues?",
       x = "Average Passing Statistics", y = "Value (Actual Values)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

q7chart <- ggplotly(ch7)
q7chart

# Show the two together
q7plt <- subplot(q4chart, q7chart)
q7plt



```


```{r}
#Want players with the worst misconduct (Ignore players who have recieved more than one red card/2 yellows a game as its not possible)
q6df <- select(df, Player, Comp, Fls, CrdY, CrdR,TklDriPast, MP, Squad, Pos) %>% subset( MP > 14  & Fls > 2)
#Makes the tool tip more informative with proper names
names(q6df)[4] <- "YellowCards"
names(q6df)[5] <- "RedCards"
names(q6df)[6] <- "DribbledPastByOpp"
names(q6df)[7] <- "MatchesPlayed"
q6df
q6chr <- ggplot(q6df, aes(x=Fls, y = DribbledPastByOpp, a= Player,b=MatchesPlayed, color=YellowCards )) + geom_point() + labs(title = "Do players who get dribbled past more often tend to foul more ?
", x = "Number of Fouls",
y = "Number of times dribbled past per game", color = "Number of yellow cards per game") + scale_color_gradient(low="green", high="red") + facet_wrap(~ Comp)
q6chr <- ggplotly(q6chr, tooltip = c("Player", "Fls", "YellowCards", "DribbledPastByOpp", "MatchesPlayed"))
q6chr
```

